// Generated by `weft codegen`. Do not edit by hand.
// Augments `WorkflowRegistry` to type engine and client call sites
// (start/schedule input and handle.result() output) per workflow.
/* eslint-disable */

declare module '@lostgradient/weft' {
  interface WorkflowRegistry {
    "welcome": { input: { "name": string; }; output: { "greeting": string; } };
  }
}

export {};
