import {
  ActivityAsyncPendingEvent,
  ActivityCompletedEvent,
  ActivityFailedEvent,
  ActivityStartedEvent,
  AlertFiredEvent,
  AlertResolvedEvent,
  AttributesChangedEvent,
  ConstraintViolatedEvent,
  ScheduleFiredEvent,
  ScheduleMissedFireEvent,
  SignalDeliveredEvent,
  SignalReceivedEvent,
  TaskResultDeadLetteredEvent,
  UpdateCompletedEvent,
  UpdateReceivedEvent,
  WorkerConnectedEvent,
  WorkerDisconnectedEvent,
  WorkflowCancelledEvent,
  WorkflowCompletedEvent,
  WorkflowFailedEvent,
  WorkflowResumedEvent,
  WorkflowStartedEvent,
  WorkflowSuspendedEvent,
  WorkflowTeardownEvent,
  WorkflowTimedOutEvent,
} from '../../core/events.ts';
import { ReviewCompletedEvent, ReviewRequestedEvent } from '../../core/review/events.ts';

export const TOKEN_EVENT_TYPE = 'stream:token';

export const CLIENT_VISIBLE_EVENT_TYPES = [
  WorkflowStartedEvent.type,
  WorkflowCompletedEvent.type,
  WorkflowFailedEvent.type,
  WorkflowCancelledEvent.type,
  WorkflowTimedOutEvent.type,
  WorkflowResumedEvent.type,
  WorkflowSuspendedEvent.type,
  WorkflowTeardownEvent.type,
  ActivityStartedEvent.type,
  ActivityCompletedEvent.type,
  ActivityFailedEvent.type,
  ActivityAsyncPendingEvent.type,
  TaskResultDeadLetteredEvent.type,
  TOKEN_EVENT_TYPE,
  SignalReceivedEvent.type,
  SignalDeliveredEvent.type,
  AttributesChangedEvent.type,
  UpdateReceivedEvent.type,
  UpdateCompletedEvent.type,
  ScheduleFiredEvent.type,
  ScheduleMissedFireEvent.type,
  ReviewRequestedEvent.type,
  ReviewCompletedEvent.type,
  AlertFiredEvent.type,
  AlertResolvedEvent.type,
  ConstraintViolatedEvent.type,
  WorkerConnectedEvent.type,
  WorkerDisconnectedEvent.type,
] as const;
