// Generated by `weft codegen`. Do not edit by hand.
// Augments `WorkflowRegistry` to type engine and client call sites
// (start/schedule input and handle.result() output) per workflow.
/* eslint-disable */

type __WeftSchema_2d70173cbf0665ac = { "name": string; };

declare module '@lostgradient/weft' {
  interface WorkflowRegistry {
    "farewell": { input: __WeftSchema_2d70173cbf0665ac; output: { "message": string; }; revision: "sha256:c97ef278988bff8fab840890dd2d565a74590b16a50db9576b5cb195bb44d95a"; workflowVersion: "0.0.0" };
    "welcome": { input: __WeftSchema_2d70173cbf0665ac; output: { "greeting": string; }; revision: "sha256:459490e35ec0c6cab26b944ac5d023f0d3a581f3ab8229cd2ac3b500f779f924"; workflowVersion: "0.0.0" };
  }
}

export {};
