/**
 * Worker implementation type emission for `weft codegen --target worker`.
 *
 * @module cli/codegen-emit-worker
 */

import { compareCodepoint } from '../core/compare-codepoint.ts';
import { jsonSchemaToTypeScript } from '../index.ts';
import { emitPropertyKey, emitStringLiteral } from '../json-schema/codegen-emit.ts';
import type { CodegenActivityContract, CodegenWorkflowEntry } from './codegen-emit-registry.ts';

function sortedEntries<T>(record: Readonly<Record<string, T>>): Array<[string, T]> {
  return Object.entries(record).toSorted(([a], [b]) => compareCodepoint(a, b));
}

function schemaType(schema: Record<string, unknown> | undefined): string {
  return jsonSchemaToTypeScript(schema);
}

function emitActivityType(
  name: string,
  contract: CodegenActivityContract,
  packageName: string,
): string {
  const input = schemaType(contract.inputSchema);
  const output = schemaType(contract.outputSchema);
  return `    ${emitPropertyKey(name)}: (input: ${input}, context?: import(${emitStringLiteral(packageName)}).RemoteActivityContext) => ${output} | Promise<${output}>;`;
}

function emitWorkflowType(
  name: string,
  entry: CodegenWorkflowEntry,
  packageName: string,
): string[] {
  const typeName = `__WeftWorker_${name.replaceAll(/[^A-Za-z0-9_$]/g, '_')}`;
  const activityLines = sortedEntries(entry.activities ?? {}).map(([activityName, contract]) =>
    emitActivityType(activityName, contract, packageName),
  );
  const block =
    activityLines.length === 0
      ? [
          `type ${typeName} = { readonly name: ${emitStringLiteral(name)}; readonly activities: {} };`,
        ]
      : [
          `type ${typeName} = {`,
          `  readonly name: ${emitStringLiteral(name)};`,
          '  readonly activities: {',
          ...activityLines,
          '  };',
          '};',
        ];
  return block;
}

export function emitWorkerImplementationModule(
  activeWorkflows: Record<string, CodegenWorkflowEntry>,
  packageName: string,
): string {
  const authoringPackageName = `${packageName}/worker/generated-authoring`;
  const workflowEntries = sortedEntries(activeWorkflows);
  const typeBlocks = workflowEntries.flatMap(([name, entry]) => [
    ...emitWorkflowType(name, entry, authoringPackageName),
    '',
  ]);
  const workflowProperties = workflowEntries.map(([name]) => {
    const typeName = `__WeftWorker_${name.replaceAll(/[^A-Za-z0-9_$]/g, '_')}`;
    return `    ${emitPropertyKey(name)}: ${typeName};`;
  });
  const workflowMap =
    workflowProperties.length === 0
      ? 'type __WeftGeneratedWorkerWorkflows = {};'
      : ['type __WeftGeneratedWorkerWorkflows = {', ...workflowProperties, '};'].join('\n');

  return [
    '// Generated by `weft codegen --target worker`. Do not edit by hand.',
    `import { defineWorker } from '${authoringPackageName}';`,
    '',
    ...typeBlocks,
    workflowMap,
    '',
    'export function defineGeneratedWorker(options: {',
    '  deployment: string;',
    '  workflows: __WeftGeneratedWorkerWorkflows;',
    '}) {',
    '  return defineWorker(options);',
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
}
