#!/usr/bin/env bun

import { mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';

import { format, resolveConfig } from 'prettier';

import type {
  CatalogOperationSnapshot,
  CatalogSnapshot,
} from '../src/cli/operation-catalog-snapshot.ts';
import { createCatalogSnapshot } from '../src/cli/operation-catalog-snapshot.ts';
import { compareStrings } from '../src/server/json-schema-utilities.ts';

export const OPERATION_CLIENT_PATH = 'src/cli/generated/operation-client.generated.ts';

export async function createOperationClientSource(snapshot: CatalogSnapshot): Promise<string> {
  const operations = snapshot.operations
    .filter((operation) => operation.kind === 'unary' && operation.transports.jsonRpcHttp)
    .toSorted((left, right) => compareStrings(left.name, right.name));
  const names = operations.map((operation) => `  '${operation.name}',`);
  const entries = operations.map(operationToTypeEntry);
  const source = `/* generated by scripts/generate-operation-client.ts; do not edit by hand */
/* oxlint-disable max-lines -- generated catalog clients are intentionally dense; rejected: splitting generated output across hidden fragments */

import {
  createCatalogWeftClient,
  type CatalogWeftClient,
  type WeftClientConnection,
} from '../operation-client-runtime.ts';

export const CATALOG_OPERATION_NAMES = [
${names.join('\n')}
] as const;

export type CatalogOperationName = (typeof CATALOG_OPERATION_NAMES)[number];

export type CatalogOperationTypes = {
${entries.join('\n')}
};

export type WeftClient = CatalogWeftClient<CatalogOperationTypes>;

export function createWeftClient(connection: WeftClientConnection = {}): WeftClient {
  return createCatalogWeftClient<CatalogOperationTypes>(CATALOG_OPERATION_NAMES, connection);
}
`;
  const prettierConfiguration = await resolveConfig(OPERATION_CLIENT_PATH);
  return format(
    source,
    prettierConfiguration === null
      ? { filepath: OPERATION_CLIENT_PATH }
      : { ...prettierConfiguration, filepath: OPERATION_CLIENT_PATH },
  );
}

if (import.meta.main) {
  await mkdir(dirname(OPERATION_CLIENT_PATH), { recursive: true });
  await Bun.write(
    OPERATION_CLIENT_PATH,
    await createOperationClientSource(createCatalogSnapshot()),
  );
  console.log(`wrote ${OPERATION_CLIENT_PATH}`);
}

function operationToTypeEntry(operation: CatalogOperationSnapshot): string {
  const faults = operation.producibleFaults.length
    ? operation.producibleFaults.map((fault) => `'${fault}'`).join(' | ')
    : 'never';
  return `  '${operation.name}': {
    readonly input: ${jsonSchemaToType(operation.inputSchema)};
    readonly output: ${jsonSchemaToType(operation.outputSchema)};
    readonly faults: ${faults};
  };`;
}

function jsonSchemaToType(schema: Record<string, unknown>): string {
  const type = schema['type'];
  if (type === 'string') return 'string';
  if (type === 'number' || type === 'integer') return 'number';
  if (type === 'boolean') return 'boolean';
  if (type === 'null') return 'null';
  if (type === 'array') {
    const items = schema['items'];
    return `ReadonlyArray<${isRecord(items) ? jsonSchemaToType(items) : 'unknown'}>`;
  }
  if (Array.isArray(type)) {
    return type
      .map((entry) => (typeof entry === 'string' ? jsonSchemaToType({ type: entry }) : 'unknown'))
      .join(' | ');
  }
  if (type === 'object' || isRecord(schema['properties'])) {
    const properties = schema['properties'];
    if (!isRecord(properties)) return 'Record<string, unknown>';
    const required = new Set(
      Array.isArray(schema['required'])
        ? schema['required'].filter((entry): entry is string => typeof entry === 'string')
        : [],
    );
    const fields = Object.entries(properties).map(([name, propertySchema]) => {
      const optional = required.has(name) ? '' : '?';
      return `readonly ${JSON.stringify(name)}${optional}: ${
        isRecord(propertySchema) ? jsonSchemaToType(propertySchema) : 'unknown'
      };`;
    });
    return `{ ${fields.join(' ')} }`;
  }
  return 'unknown';
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
