#!/usr/bin/env bun

import { mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';

import { format, resolveConfig } from 'prettier';

import type {
  CatalogOperationSnapshot,
  CatalogSnapshot,
} from '../src/cli/operation-catalog-snapshot.ts';
import { createCatalogSnapshot } from '../src/cli/operation-catalog-snapshot.ts';
import { compareStrings } from '../src/server/json-schema-utilities.ts';

export const OPERATION_CLIENT_PATH = 'src/cli/generated/operation-client.generated.ts';

/**
 * Hoist a repeated object shape into a named alias only when it appears at least
 * twice. Below this it is unique and aliasing would only add indirection.
 */
const MINIMUM_OCCURRENCES = 2;

/**
 * Object shapes with at least this many fields are always worth a named alias
 * once they repeat. Smaller shapes (e.g. a single-field `{ key: string }`) are
 * left inline unless they repeat unusually often (see {@link FREQUENT_OCCURRENCES}).
 */
const LARGE_FIELD_COUNT = 3;

/**
 * The minimum field count and occurrence count under which a small (2-field)
 * shape still earns an alias. Keeps trivial 1-field objects inline while
 * de-duplicating genuinely repeated small records.
 */
const SMALL_FIELD_COUNT = 2;
const FREQUENT_OCCURRENCES = 3;

/** Number of PascalCased field-name fragments folded into a readable alias hint. */
const HINT_FIELD_LIMIT = 3;
/** Maximum length of the readable hint portion of an alias name. */
const HINT_MAX_LENGTH = 24;

/**
 * A normalized type node — the single source of truth for both the structural
 * dedup key and the emitted TypeScript text. Two nodes share a `canonicalKey`
 * if and only if they would render to identical TypeScript.
 */
type TypeNode =
  | { readonly kind: 'primitive'; readonly text: string }
  | { readonly kind: 'array'; readonly element: TypeNode }
  | { readonly kind: 'union'; readonly members: ReadonlyArray<TypeNode> }
  | { readonly kind: 'record' }
  | { readonly kind: 'object'; readonly fields: ReadonlyArray<ObjectField> };

type ObjectField = {
  readonly name: string;
  readonly optional: boolean;
  readonly value: TypeNode;
};

export async function createOperationClientSource(snapshot: CatalogSnapshot): Promise<string> {
  const operations = snapshot.operations
    .filter((operation) => operation.kind === 'unary' && operation.transports.jsonRpcHttp)
    .toSorted((left, right) => compareStrings(left.name, right.name));
  const names = operations.map((operation) => `  '${operation.name}',`);

  const roots = operations.flatMap((operation) => [
    schemaToNode(operation.inputSchema),
    schemaToNode(operation.outputSchema),
  ]);

  const aliasNameByKey = selectAliases(roots);
  const entries = operations.map((operation) => operationToTypeEntry(operation, aliasNameByKey));
  const aliasDeclarations = renderAliasDeclarations(aliasNameByKey);

  const aliasBlock = aliasDeclarations.length ? `\n${aliasDeclarations.join('\n')}\n` : '';

  const source = `/* generated by scripts/generate-operation-client.ts; do not edit by hand */
/* oxlint-disable max-lines -- generated catalog clients are intentionally dense; rejected: splitting generated output across hidden fragments */

import {
  createCatalogWeftClient,
  httpJsonRpcTransport,
  type CatalogWeftClient,
  type WeftClientConnection,
} from '../operation-client-runtime.ts';

export const CATALOG_OPERATION_NAMES = [
${names.join('\n')}
] as const;

export type CatalogOperationName = (typeof CATALOG_OPERATION_NAMES)[number];
${aliasBlock}
export type CatalogOperationTypes = {
${entries.join('\n')}
};

export type WeftClient = CatalogWeftClient<CatalogOperationTypes>;

export function createWeftClient(connection: WeftClientConnection = {}): WeftClient {
  return createCatalogWeftClient<CatalogOperationTypes>(
    CATALOG_OPERATION_NAMES,
    httpJsonRpcTransport(connection),
  );
}
`;
  const prettierConfiguration = await resolveConfig(OPERATION_CLIENT_PATH);
  return format(
    source,
    prettierConfiguration === null
      ? { filepath: OPERATION_CLIENT_PATH }
      : { ...prettierConfiguration, filepath: OPERATION_CLIENT_PATH },
  );
}

if (import.meta.main) {
  await mkdir(dirname(OPERATION_CLIENT_PATH), { recursive: true });
  await Bun.write(
    OPERATION_CLIENT_PATH,
    await createOperationClientSource(createCatalogSnapshot()),
  );
  console.log(`wrote ${OPERATION_CLIENT_PATH}`);
}

function operationToTypeEntry(
  operation: CatalogOperationSnapshot,
  aliasNameByKey: ReadonlyMap<string, string>,
): string {
  const faults = operation.producibleFaults.length
    ? operation.producibleFaults.map((fault) => `'${fault}'`).join(' | ')
    : 'never';
  const input = renderRoot(schemaToNode(operation.inputSchema), aliasNameByKey);
  const output = renderRoot(schemaToNode(operation.outputSchema), aliasNameByKey);
  return `  '${operation.name}': {
    readonly input: ${input};
    readonly output: ${output};
    readonly faults: ${faults};
  };`;
}

/**
 * Parse a JSON Schema fragment into a normalized {@link TypeNode}. Reproduces
 * exactly the schema subset the emitter supports: primitives, arrays,
 * `type: []` string unions, objects (honoring `required`), no-`properties`
 * objects as `Record<string, unknown>`, and an `unknown` fallback for every
 * other schema feature (enum, const, anyOf/oneOf/allOf, additionalProperties,
 * nullable patterns).
 */
function schemaToNode(schema: Record<string, unknown>): TypeNode {
  const type = schema['type'];
  if (type === 'string') return { kind: 'primitive', text: 'string' };
  if (type === 'number' || type === 'integer') return { kind: 'primitive', text: 'number' };
  if (type === 'boolean') return { kind: 'primitive', text: 'boolean' };
  if (type === 'null') return { kind: 'primitive', text: 'null' };
  if (type === 'array') {
    const items = schema['items'];
    return {
      kind: 'array',
      element: isRecord(items) ? schemaToNode(items) : { kind: 'primitive', text: 'unknown' },
    };
  }
  if (Array.isArray(type)) {
    return {
      kind: 'union',
      members: type.map((entry) =>
        typeof entry === 'string'
          ? schemaToNode({ type: entry })
          : { kind: 'primitive', text: 'unknown' },
      ),
    };
  }
  if (type === 'object' || isRecord(schema['properties'])) {
    const properties = schema['properties'];
    if (!isRecord(properties)) return { kind: 'record' };
    const required = new Set(
      Array.isArray(schema['required'])
        ? schema['required'].filter((entry): entry is string => typeof entry === 'string')
        : [],
    );
    const fields = Object.entries(properties)
      .map(([name, propertySchema]) => ({
        name,
        optional: !required.has(name),
        value: isRecord(propertySchema)
          ? schemaToNode(propertySchema)
          : ({ kind: 'primitive', text: 'unknown' } satisfies TypeNode),
      }))
      .toSorted((left, right) => compareStrings(left.name, right.name));
    return { kind: 'object', fields };
  }
  return { kind: 'primitive', text: 'unknown' };
}

/**
 * Render a {@link TypeNode} to TypeScript. When a child node's
 * {@link canonicalKey} is present in `aliasNameByKey`, the alias name is
 * substituted in place of inlining the shape. `suppressKey` prevents an alias
 * body from referencing itself (which would emit `type X = X`).
 */
function renderNode(
  node: TypeNode,
  aliasNameByKey: ReadonlyMap<string, string>,
  suppressKey?: string,
): string {
  switch (node.kind) {
    case 'primitive':
      return node.text;
    case 'record':
      return 'Record<string, unknown>';
    case 'array':
      return `ReadonlyArray<${renderChild(node.element, aliasNameByKey)}>`;
    case 'union':
      return node.members.map((member) => renderChild(member, aliasNameByKey)).join(' | ');
    case 'object': {
      const fields = node.fields.map((field) => {
        const optional = field.optional ? '?' : '';
        return `readonly ${JSON.stringify(field.name)}${optional}: ${renderChild(
          field.value,
          aliasNameByKey,
        )};`;
      });
      return `{ ${fields.join(' ')} }`;
    }
  }

  function renderChild(child: TypeNode, aliases: ReadonlyMap<string, string>): string {
    const key = canonicalKey(child);
    if (key !== suppressKey) {
      const alias = aliases.get(key);
      if (alias !== undefined) return alias;
    }
    return renderNode(child, aliases, suppressKey);
  }
}

/**
 * Render a top-level node (an operation input/output position). Unlike
 * {@link renderNode}, this substitutes the alias name when the node *itself* is
 * hoisted — so two operations with an identical whole-object input both collapse
 * to the same alias reference.
 */
function renderRoot(node: TypeNode, aliasNameByKey: ReadonlyMap<string, string>): string {
  const alias = aliasNameByKey.get(canonicalKey(node));
  if (alias !== undefined) return alias;
  return renderNode(node, aliasNameByKey);
}

/** Deterministic structural key for a node; equal iff the emitted text is equal. */
function canonicalKey(node: TypeNode): string {
  return JSON.stringify(node);
}

/**
 * Select which structural shapes to hoist into aliases and assign each a stable
 * name. Performs a final prune-to-fixed-point so that every surviving alias is
 * referenced at least twice across the emitted alias bodies and operation entries.
 */
function selectAliases(roots: ReadonlyArray<TypeNode>): Map<string, string> {
  const counts = new Map<string, { count: number; node: TypeNode }>();
  for (const root of roots) collectCounts(root, counts);

  const candidates = new Map<string, TypeNode>();
  for (const [key, { count, node }] of counts) {
    if (isHoistWorthy(node, count)) candidates.set(key, node);
  }

  let aliasNameByKey = assignAliasNames(candidates);

  // Prune aliases whose final non-declaration reference count falls below the
  // minimum. Dropping a parent can lower a child's references, so iterate.
  for (;;) {
    const references = countAliasReferences(aliasNameByKey, roots);
    const survivors = new Map<string, TypeNode>();
    for (const [key, node] of candidates) {
      const name = aliasNameByKey.get(key);
      if (name !== undefined && (references.get(name) ?? 0) >= MINIMUM_OCCURRENCES) {
        survivors.set(key, node);
      }
    }
    if (survivors.size === candidates.size) break;
    candidates.clear();
    for (const [key, node] of survivors) candidates.set(key, node);
    aliasNameByKey = assignAliasNames(candidates);
  }

  return aliasNameByKey;
}

/** Increment the occurrence count for `node` and recurse into its children. */
function collectCounts(
  node: TypeNode,
  counts: Map<string, { count: number; node: TypeNode }>,
): void {
  const key = canonicalKey(node);
  const existing = counts.get(key);
  if (existing) existing.count += 1;
  else counts.set(key, { count: 1, node });

  if (node.kind === 'array') collectCounts(node.element, counts);
  else if (node.kind === 'union') for (const member of node.members) collectCounts(member, counts);
  else if (node.kind === 'object')
    for (const field of node.fields) collectCounts(field.value, counts);
}

function isHoistWorthy(node: TypeNode, count: number): boolean {
  if (node.kind !== 'object') return false;
  if (count < MINIMUM_OCCURRENCES) return false;
  const fieldCount = node.fields.length;
  if (fieldCount >= LARGE_FIELD_COUNT) return true;
  return fieldCount >= SMALL_FIELD_COUNT && count >= FREQUENT_OCCURRENCES;
}

/**
 * Assign a stable, readable, content-derived name to each candidate shape.
 * `hashFn` is injectable so the collision guard can be exercised in tests;
 * it defaults to the real FNV-1a hash.
 */
export function assignAliasNames(
  candidates: ReadonlyMap<string, TypeNode>,
  hashFn: (value: string) => string = fnv1a,
): Map<string, string> {
  const aliasNameByKey = new Map<string, string>();
  const keyByName = new Map<string, string>();
  // Deterministic assignment order so names never depend on Map insertion order.
  const sortedKeys = [...candidates.keys()].toSorted(compareStrings);
  for (const key of sortedKeys) {
    const node = candidates.get(key)!;
    const name = aliasNameFor(node, hashFn);
    const existing = keyByName.get(name);
    if (existing !== undefined && existing !== key) {
      throw new Error(`alias name collision: ${name} for ${existing} and ${key}`);
    }
    keyByName.set(name, key);
    aliasNameByKey.set(key, name);
  }
  return aliasNameByKey;
}

/**
 * Build the alias name `Shared<hint>_<hash>` for an object node: a readable
 * hint drawn from the first sorted field names plus a stable content hash.
 */
export function aliasNameFor(node: TypeNode, hashFn: (value: string) => string = fnv1a): string {
  const fields = node.kind === 'object' ? node.fields : [];
  const hint = fields
    .slice(0, HINT_FIELD_LIMIT)
    .map((field) => toPascalCase(field.name))
    .join('')
    .slice(0, HINT_MAX_LENGTH);
  return `Shared${hint}_${hashFn(canonicalKey(node))}`;
}

/** Count non-declaration references to each alias name across all rendered output. */
function countAliasReferences(
  aliasNameByKey: ReadonlyMap<string, string>,
  roots: ReadonlyArray<TypeNode>,
): Map<string, number> {
  const references = new Map<string, number>();
  for (const name of aliasNameByKey.values()) references.set(name, 0);

  const tally = (text: string) => {
    for (const [, name] of aliasNameByKey) {
      const matches = text.match(new RegExp(`\\b${name}\\b`, 'g'));
      if (matches) references.set(name, (references.get(name) ?? 0) + matches.length);
    }
  };

  // References from operation entries (roots may themselves be aliases).
  for (const root of roots) tally(renderRoot(root, aliasNameByKey));
  // References between alias bodies (each rendered with self suppressed).
  for (const body of aliasBodies(aliasNameByKey, roots).values()) tally(body);

  return references;
}

/** Render each alias body once (self-suppressed), keyed by alias name. */
function aliasBodies(
  aliasNameByKey: ReadonlyMap<string, string>,
  roots: ReadonlyArray<TypeNode>,
): Map<string, string> {
  const nodeByKey = new Map<string, TypeNode>();
  const collect = (node: TypeNode) => {
    const key = canonicalKey(node);
    if (aliasNameByKey.has(key) && !nodeByKey.has(key)) nodeByKey.set(key, node);
    if (node.kind === 'array') collect(node.element);
    else if (node.kind === 'union') for (const member of node.members) collect(member);
    else if (node.kind === 'object') for (const field of node.fields) collect(field.value);
  };
  for (const root of roots) collect(root);

  const bodies = new Map<string, string>();
  for (const [key, node] of nodeByKey) {
    const name = aliasNameByKey.get(key)!;
    bodies.set(name, renderNode(node, aliasNameByKey, key));
  }
  return bodies;
}

/** Render the `type Shared… = …;` declarations, sorted by alias name. */
function renderAliasDeclarations(aliasNameByKey: ReadonlyMap<string, string>): string[] {
  // The canonical key is `JSON.stringify(node)`, so each alias node is recovered
  // by parsing its key. Each body is rendered with self suppressed so nested
  // aliases substitute but the alias never references itself.
  const entries = [...aliasNameByKey.entries()].toSorted(([, left], [, right]) =>
    compareStrings(left, right),
  );
  return entries.map(([key, name]) => {
    const body = renderNode(parseKey(key), aliasNameByKey, key);
    return `type ${name} = ${body};`;
  });
}

/** Parse a canonical key back into its {@link TypeNode}. */
function parseKey(key: string): TypeNode {
  return JSON.parse(key) as TypeNode;
}

function toPascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter((segment) => segment.length > 0)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

/**
 * 32-bit FNV-1a hash, formatted as 8 lowercase hex characters. Uses `Math.imul`
 * and `>>> 0` normalization to stay within unsigned 32-bit semantics regardless
 * of JavaScript's signed-int behavior.
 */
function fnv1a(value: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
    hash >>>= 0;
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export { canonicalKey, renderNode, schemaToNode };
export type { TypeNode };
