#!/usr/bin/env bun

import { mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';

import { format, resolveConfig } from 'prettier';

import type {
  CatalogOperationSnapshot,
  CatalogSnapshot,
} from '../src/cli/operation-catalog-snapshot.ts';
import { createCatalogSnapshot } from '../src/cli/operation-catalog-snapshot.ts';
import { compareStrings } from '../src/server/json-schema-utilities.ts';

export const OPERATION_CLIENT_PATH = 'src/cli/generated/operation-client.generated.ts';

/**
 * Hoist a repeated object shape into a named alias only when it appears at least
 * twice. Below this it is unique and aliasing would only add indirection.
 */
const MINIMUM_OCCURRENCES = 2;

/**
 * Object shapes with at least this many fields are always worth a named alias
 * once they repeat. Smaller shapes (e.g. a single-field `{ key: string }`) are
 * left inline unless they repeat unusually often (see {@link FREQUENT_OCCURRENCES}).
 */
const LARGE_FIELD_COUNT = 3;

/**
 * The minimum field count and occurrence count under which a small (2-field)
 * shape still earns an alias. Keeps trivial 1-field objects inline while
 * de-duplicating genuinely repeated small records.
 */
const SMALL_FIELD_COUNT = 2;
const FREQUENT_OCCURRENCES = 3;

/** Number of PascalCased field-name fragments folded into a readable alias hint. */
const HINT_FIELD_LIMIT = 3;
/** Maximum length of the readable hint portion of an alias name. */
const HINT_MAX_LENGTH = 24;

/**
 * A normalized type node — the single source of truth for both the structural
 * dedup key and the emitted TypeScript text. Two nodes share a `canonicalKey`
 * if and only if they would render to identical TypeScript.
 */
type TypeNode =
  | { readonly kind: 'primitive'; readonly text: string }
  | { readonly kind: 'array'; readonly element: TypeNode }
  | { readonly kind: 'union'; readonly members: ReadonlyArray<TypeNode> }
  | { readonly kind: 'record' }
  | { readonly kind: 'object'; readonly fields: ReadonlyArray<ObjectField> };

type ObjectField = {
  readonly name: string;
  readonly optional: boolean;
  readonly value: TypeNode;
};

export async function createOperationClientSource(snapshot: CatalogSnapshot): Promise<string> {
  const catalogOperations = snapshot.operations
    .filter((operation) => operation.kind === 'unary' && operation.transports.jsonRpcHttp)
    .toSorted((left, right) => compareStrings(left.name, right.name));
  const restOnlyOperations = snapshot.operations
    .filter(isGenericRestClientOperation)
    .toSorted((left, right) => compareStrings(left.name, right.name));
  const clientOperations = [...catalogOperations, ...restOnlyOperations].toSorted((left, right) =>
    compareStrings(left.name, right.name),
  );
  const catalogNames = catalogOperations.map((operation) => `  '${operation.name}',`);
  const clientNames = clientOperations.map((operation) => `  '${operation.name}',`);
  const restBindings = restOnlyOperations.map((operation) => {
    const rest = operation.rest;
    if (rest === undefined) throw new Error(`missing REST binding for ${operation.name}`);
    const clientPath = rest.path.replace(/^\/v1/, '');
    return `  '${operation.name}': ${JSON.stringify({ ...rest, path: clientPath })},`;
  });

  const roots = clientOperations.flatMap((operation) => [
    schemaToNode(operation.inputSchema),
    schemaToNode(operation.outputSchema),
  ]);

  const { aliasNameByKey, nodeByKey } = selectAliases(roots);
  const entries = clientOperations.map((operation) =>
    operationToTypeEntry(operation, aliasNameByKey),
  );
  const aliasDeclarations = renderAliasDeclarations(aliasNameByKey, nodeByKey);

  const aliasBlock = aliasDeclarations.length ? `\n${aliasDeclarations.join('\n')}\n` : '';

  const source = `/* generated by scripts/generate-operation-client.ts; do not edit by hand */
/* oxlint-disable max-lines -- generated catalog clients are intentionally dense; rejected: splitting generated output across hidden fragments */

import {
  createCatalogWeftClient,
  httpJsonRpcTransport,
  type ClientRestOperationBinding,
  type CatalogWeftClient,
  type WeftClientConnection,
} from '../operation-client-runtime.ts';

export const CATALOG_OPERATION_NAMES = [
${catalogNames.join('\n')}
] as const;

export type CatalogOperationName = (typeof CATALOG_OPERATION_NAMES)[number];

export const CLIENT_OPERATION_NAMES = [
${clientNames.join('\n')}
] as const;

export type ClientOperationName = (typeof CLIENT_OPERATION_NAMES)[number];

export const CLIENT_REST_OPERATION_BINDINGS = {
${restBindings.join('\n')}
} as const satisfies Readonly<Record<string, ClientRestOperationBinding>>;
${aliasBlock}
export type ClientOperationTypes = {
${entries.join('\n')}
};

export type CatalogOperationTypes = Pick<ClientOperationTypes, CatalogOperationName>;

export type WeftClient = CatalogWeftClient<CatalogOperationTypes>;
export type ClientOperations = CatalogWeftClient<ClientOperationTypes>;

export function createWeftClient(connection: WeftClientConnection = {}): WeftClient {
  return createCatalogWeftClient<CatalogOperationTypes>(
    CATALOG_OPERATION_NAMES,
    httpJsonRpcTransport(connection),
  );
}
`;
  const prettierConfiguration = await resolveConfig(OPERATION_CLIENT_PATH);
  return format(source, {
    ...prettierConfiguration,
    filepath: OPERATION_CLIENT_PATH,
  });
}

/**
 * Ordinary REST-only unary operations can use the generated JSON request
 * transport. Storage stays on `client.storage`: its octet-stream and NDJSON
 * wire formats require a byte-oriented facade rather than schema-shaped JSON.
 */
function isGenericRestClientOperation(operation: CatalogOperationSnapshot): boolean {
  if (operation.kind !== 'unary') return false;
  if (!operation.transports.http || operation.transports.jsonRpcHttp) return false;
  if (operation.tags.includes('Storage')) return false;
  const rest = operation.rest;
  if (rest === undefined || rest.success.kind === 'streaming') return false;
  return Object.values(rest.inputSources).every(
    (source) => source.kind !== 'body' || source.mediaType !== 'application/octet-stream',
  );
}

if (import.meta.main) {
  await mkdir(dirname(OPERATION_CLIENT_PATH), { recursive: true });
  await Bun.write(
    OPERATION_CLIENT_PATH,
    await createOperationClientSource(createCatalogSnapshot()),
  );
  console.log(`wrote ${OPERATION_CLIENT_PATH}`);
}

function operationToTypeEntry(
  operation: CatalogOperationSnapshot,
  aliasNameByKey: ReadonlyMap<string, string>,
): string {
  const faults = operation.producibleFaults.length
    ? operation.producibleFaults.map((fault) => `'${fault}'`).join(' | ')
    : 'never';
  const input = renderRoot(schemaToNode(operation.inputSchema), aliasNameByKey);
  const output = renderRoot(schemaToNode(operation.outputSchema), aliasNameByKey);
  return `  '${operation.name}': {
    readonly input: ${input};
    readonly output: ${output};
    readonly faults: ${faults};
  };`;
}

/**
 * Return the members of an all-string `enum`, or `undefined` when the schema has
 * no `enum` or any member is not a string. A single-quoted string-literal union
 * is emitted for these; mixed or non-string enums fall through to the `unknown`
 * fallback rather than guessing a representation.
 */
function stringEnumMembers(schema: Record<string, unknown>): readonly string[] | undefined {
  const values = schema['enum'];
  if (!Array.isArray(values) || values.length === 0) return undefined;
  if (!values.every((value): value is string => typeof value === 'string')) return undefined;
  return values;
}

/**
 * Parse a JSON Schema fragment into a normalized {@link TypeNode}. Reproduces
 * exactly the schema subset the emitter supports: primitives, arrays,
 * string `enum` literal unions, `type: []` string unions, objects (honoring
 * `required`), no-`properties` objects as `Record<string, unknown>`, and an
 * `unknown` fallback for every other schema feature (non-string `enum`, const,
 * anyOf/oneOf/allOf, additionalProperties, nullable patterns).
 */
function schemaToNode(schema: Record<string, unknown>): TypeNode {
  // A string `enum` is tighter than its `type: 'string'`, so emit the literal
  // union and preserve the operation's discriminant (e.g. startorsignal's
  // `outcome: 'started' | 'signalled'`) instead of widening to `string`. Members
  // stay in schema order for deterministic output. Non-string enums fall through.
  const stringEnum = stringEnumMembers(schema);
  if (stringEnum !== undefined) {
    return {
      kind: 'union',
      // `JSON.stringify` produces a TypeScript-valid double-quoted string literal
      // with proper escaping, so enum values containing quotes, backslashes, or
      // newlines emit a correct literal rather than via raw interpolation.
      members: stringEnum.map((value) => ({ kind: 'primitive', text: JSON.stringify(value) })),
    };
  }
  const type = schema['type'];
  if (type === 'string') return { kind: 'primitive', text: 'string' };
  if (type === 'number' || type === 'integer') return { kind: 'primitive', text: 'number' };
  if (type === 'boolean') return { kind: 'primitive', text: 'boolean' };
  if (type === 'null') return { kind: 'primitive', text: 'null' };
  if (type === 'array') {
    const items = schema['items'];
    return {
      kind: 'array',
      element: isRecord(items) ? schemaToNode(items) : { kind: 'primitive', text: 'unknown' },
    };
  }
  if (Array.isArray(type)) {
    return {
      kind: 'union',
      members: type.map((entry) =>
        typeof entry === 'string'
          ? schemaToNode({ type: entry })
          : { kind: 'primitive', text: 'unknown' },
      ),
    };
  }
  if (type === 'object' || isRecord(schema['properties'])) {
    const properties = schema['properties'];
    if (!isRecord(properties)) return { kind: 'record' };
    const required = new Set(
      Array.isArray(schema['required'])
        ? schema['required'].filter((entry): entry is string => typeof entry === 'string')
        : [],
    );
    // Snapshot schemas arrive with keys already canonicalized (alphabetical), so
    // this sort is a no-op on the real catalog and preserves the prior generator's
    // field order byte-for-byte. It stays as a defensive invariant: the dedup key
    // and emitted text must be field-order-stable even if an upstream source is
    // ever not pre-canonicalized.
    const fields = Object.entries(properties)
      .map(([name, propertySchema]) => ({
        name,
        optional: !required.has(name),
        value: isRecord(propertySchema)
          ? schemaToNode(propertySchema)
          : ({ kind: 'primitive', text: 'unknown' } satisfies TypeNode),
      }))
      .toSorted((left, right) => compareStrings(left.name, right.name));
    return { kind: 'object', fields };
  }
  return { kind: 'primitive', text: 'unknown' };
}

/**
 * Render a {@link TypeNode} to TypeScript. When a child node's
 * {@link canonicalKey} is present in `aliasNameByKey`, the alias name is
 * substituted in place of inlining the shape. `suppressKey` prevents an alias
 * body from referencing itself (which would emit `type X = X`).
 */
function renderNode(
  node: TypeNode,
  aliasNameByKey: ReadonlyMap<string, string>,
  suppressKey?: string,
): string {
  // Render a child, substituting its alias name unless it is the suppressed self.
  const renderChild = (child: TypeNode): string => {
    const key = canonicalKey(child);
    if (key !== suppressKey) {
      const alias = aliasNameByKey.get(key);
      if (alias !== undefined) return alias;
    }
    return renderNode(child, aliasNameByKey, suppressKey);
  };

  switch (node.kind) {
    case 'primitive':
      return node.text;
    case 'record':
      return 'Record<string, unknown>';
    case 'array':
      return `ReadonlyArray<${renderChild(node.element)}>`;
    case 'union':
      return node.members.map((member) => renderChild(member)).join(' | ');
    case 'object': {
      const fields = node.fields.map((field) => {
        const optional = field.optional ? '?' : '';
        return `readonly ${JSON.stringify(field.name)}${optional}: ${renderChild(field.value)};`;
      });
      return `{ ${fields.join(' ')} }`;
    }
  }
}

/**
 * Render a top-level node (an operation input/output position). Unlike
 * {@link renderNode}, this substitutes the alias name when the node *itself* is
 * hoisted — so two operations with an identical whole-object input both collapse
 * to the same alias reference.
 */
function renderRoot(node: TypeNode, aliasNameByKey: ReadonlyMap<string, string>): string {
  const alias = aliasNameByKey.get(canonicalKey(node));
  if (alias !== undefined) return alias;
  return renderNode(node, aliasNameByKey);
}

/** Deterministic structural key for a node; equal iff the emitted text is equal. */
function canonicalKey(node: TypeNode): string {
  return JSON.stringify(node);
}

type AliasSelection = {
  readonly aliasNameByKey: ReadonlyMap<string, string>;
  readonly nodeByKey: ReadonlyMap<string, TypeNode>;
};

/**
 * Select which structural shapes to hoist into aliases. Prunes to a fixed point
 * so that every surviving alias is referenced at least twice across the emitted
 * alias bodies and operation entries. Returns both the name map and the original
 * nodes so declarations render without round-tripping through the string key.
 */
function selectAliases(roots: ReadonlyArray<TypeNode>): AliasSelection {
  const counts = new Map<string, { count: number; node: TypeNode }>();
  for (const root of roots) collectCounts(root, counts);

  let candidates = new Map<string, TypeNode>();
  for (const [key, { count, node }] of counts) {
    if (isHoistWorthy(node, count)) candidates.set(key, node);
  }

  // Prune aliases referenced fewer than twice once substitution is applied.
  // Dropping a parent can lower a child's reference count, so iterate to a fixed
  // point. References are counted structurally over the node graph (not by text
  // matching), so the count is exact. The loop strictly shrinks `candidates`
  // each iteration until it stabilizes, so it terminates in at most
  // `candidates.size` rounds.
  for (;;) {
    const aliasKeys = new Set(candidates.keys());
    const references = countAliasReferences(aliasKeys, roots);
    const survivors = new Map<string, TypeNode>();
    for (const [key, node] of candidates) {
      if ((references.get(key) ?? 0) >= MINIMUM_OCCURRENCES) survivors.set(key, node);
    }
    if (survivors.size === candidates.size) break;
    candidates = survivors;
  }

  return { aliasNameByKey: assignAliasNames(candidates), nodeByKey: candidates };
}

/** Increment the occurrence count for `node` and recurse into its children. */
function collectCounts(
  node: TypeNode,
  counts: Map<string, { count: number; node: TypeNode }>,
): void {
  const key = canonicalKey(node);
  const existing = counts.get(key);
  if (existing) existing.count += 1;
  else counts.set(key, { count: 1, node });

  if (node.kind === 'array') collectCounts(node.element, counts);
  else if (node.kind === 'union') for (const member of node.members) collectCounts(member, counts);
  else if (node.kind === 'object')
    for (const field of node.fields) collectCounts(field.value, counts);
}

function isHoistWorthy(node: TypeNode, count: number): boolean {
  if (node.kind !== 'object') return false;
  if (count < MINIMUM_OCCURRENCES) return false;
  const fieldCount = node.fields.length;
  if (fieldCount >= LARGE_FIELD_COUNT) return true;
  return fieldCount >= SMALL_FIELD_COUNT && count >= FREQUENT_OCCURRENCES;
}

/**
 * Assign a stable, readable, content-derived name to each candidate shape.
 * `hashFn` is injectable so the collision guard can be exercised in tests;
 * it defaults to the real FNV-1a hash.
 */
export function assignAliasNames(
  candidates: ReadonlyMap<string, TypeNode>,
  hashFn: (value: string) => string = fnv1a,
): Map<string, string> {
  const aliasNameByKey = new Map<string, string>();
  const keyByName = new Map<string, string>();
  // Deterministic assignment order so names never depend on Map insertion order.
  const sortedEntries = [...candidates.entries()].toSorted(([left], [right]) =>
    compareStrings(left, right),
  );
  for (const [key, node] of sortedEntries) {
    const name = aliasNameFor(node, hashFn);
    const existing = keyByName.get(name);
    if (existing !== undefined && existing !== key) {
      throw new Error(`alias name collision: ${name} for ${existing} and ${key}`);
    }
    keyByName.set(name, key);
    aliasNameByKey.set(key, name);
  }
  return aliasNameByKey;
}

/**
 * Build the alias name `Shared<hint>_<hash>` for an object node: a readable
 * hint drawn from the first sorted field names plus a stable content hash.
 */
export function aliasNameFor(node: TypeNode, hashFn: (value: string) => string = fnv1a): string {
  const fields = node.kind === 'object' ? node.fields : [];
  const hint = fields
    .slice(0, HINT_FIELD_LIMIT)
    .map((field) => toPascalCase(field.name))
    .join('')
    .slice(0, HINT_MAX_LENGTH);
  return `Shared${hint}_${hashFn(canonicalKey(node))}`;
}

/**
 * Count, per alias key, how many substitution sites would reference it once
 * `aliasKeys` are hoisted. Counts are structural — derived by walking the node
 * graph, never by matching rendered text. A reference is a position where a
 * hoisted key appears: a root that is itself an alias, or a child (array
 * element, object field, union member) whose key is hoisted. An alias node's
 * own body does not count as a self-reference (the body inlines its top level).
 */
function countAliasReferences(
  aliasKeys: ReadonlySet<string>,
  roots: ReadonlyArray<TypeNode>,
): Map<string, number> {
  const references = new Map<string, number>();
  for (const key of aliasKeys) references.set(key, 0);

  const bump = (key: string) => references.set(key, (references.get(key) ?? 0) + 1);

  /** Count alias references among the children of `node` (not `node` itself). */
  const countChildren = (node: TypeNode) => {
    if (node.kind === 'array') visitChild(node.element);
    else if (node.kind === 'union') for (const member of node.members) visitChild(member);
    else if (node.kind === 'object') for (const field of node.fields) visitChild(field.value);
  };

  const visitChild = (child: TypeNode) => {
    const key = canonicalKey(child);
    if (aliasKeys.has(key)) {
      // The child collapses to an alias reference; do not descend past it.
      bump(key);
      return;
    }
    countChildren(child);
  };

  // Operation entries: a root that is itself an alias is one reference.
  for (const root of roots) {
    const key = canonicalKey(root);
    if (aliasKeys.has(key)) bump(key);
    else countChildren(root);
  }

  // Alias bodies: each hoisted shape's body contributes references to the
  // nested aliases it substitutes (its own top level is inlined, not a self-ref).
  // The two steps below do DIFFERENT work and must both run for an alias node:
  // `countChildren` records this body's direct alias references (stopping at
  // alias boundaries), while the tail recursion keeps descending to discover and
  // count the bodies of aliases nested deeper. Returning early after
  // `countChildren` would miss grandchild aliases and is a bug, not an
  // optimization. `seen` makes the per-body counting idempotent across roots that
  // share a subtree.
  const seen = new Set<string>();
  const collectBodies = (node: TypeNode) => {
    const key = canonicalKey(node);
    if (aliasKeys.has(key) && !seen.has(key)) {
      seen.add(key);
      countChildren(node);
    }
    if (node.kind === 'array') collectBodies(node.element);
    else if (node.kind === 'union') for (const member of node.members) collectBodies(member);
    else if (node.kind === 'object') for (const field of node.fields) collectBodies(field.value);
  };
  for (const root of roots) collectBodies(root);

  return references;
}

/**
 * Render the `type Shared… = …;` declarations, sorted by alias name. Each body
 * is rendered from its original {@link TypeNode} with its own key suppressed, so
 * nested aliases substitute but the alias never references itself.
 */
function renderAliasDeclarations(
  aliasNameByKey: ReadonlyMap<string, string>,
  nodeByKey: ReadonlyMap<string, TypeNode>,
): string[] {
  const entries = [...aliasNameByKey.entries()].toSorted(([, left], [, right]) =>
    compareStrings(left, right),
  );
  return entries.map(([key, name]) => {
    const node = nodeByKey.get(key);
    if (node === undefined) throw new Error(`missing node for alias ${name} (${key})`);
    return `type ${name} = ${renderNode(node, aliasNameByKey, key)};`;
  });
}

function toPascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter((segment) => segment.length > 0)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

/**
 * 32-bit FNV-1a hash, formatted as 8 lowercase hex characters. Uses `Math.imul`
 * and `>>> 0` normalization to stay within unsigned 32-bit semantics regardless
 * of JavaScript's signed-int behavior.
 */
function fnv1a(value: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
    hash >>>= 0;
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export { canonicalKey, isHoistWorthy, renderNode, schemaToNode, selectAliases };
export type { AliasSelection, ObjectField, TypeNode };
