import { compareStrings } from '../src/server/json-schema-utilities.ts';
import type { CatalogOperationSnapshot } from '../src/server/operation-catalog-snapshot.ts';
import { renderRoot, schemaToNode } from './operation-client-schema.ts';

export const GENERATED_HEADER =
  '/* generated by scripts/generate-operation-client.ts; do not edit by hand */';

export type OperationDomain = {
  name: string;
  fileName: string;
  typeName: string;
  operations: CatalogOperationSnapshot[];
};

/** Catalog tags own the contract groups; task detail and bulk execution have separate schemas. */
function domainName(operation: CatalogOperationSnapshot): string {
  const tag = operation.tags[0] ?? 'Other';
  if (tag === 'Workflows' && operation.name.startsWith('weft.workflows.bulk.'))
    return 'Bulk Workflows';
  if (tag === 'Observability' && operation.name === 'weft.tasks.get') return 'Task Detail';
  if (tag === 'Observability' && operation.name.startsWith('weft.tasks.'))
    return 'Task Diagnostics';
  if (tag === 'Observability' && operation.name.startsWith('weft.workers.'))
    return 'Worker Diagnostics';
  return tag;
}

export function operationDomains(
  operations: readonly CatalogOperationSnapshot[],
): OperationDomain[] {
  const groups = new Map<string, OperationDomain>();
  for (const operation of operations) {
    const name = domainName(operation);
    let group = groups.get(name);
    if (!group) {
      const words = name.split(/[^A-Za-z0-9]+/).filter(Boolean);
      if (!words.length) throw new Error(`Operation domain requires an alphanumeric name: ${name}`);
      const slug = words.map((word) => word.toLowerCase()).join('-');
      const fileName = `${slug}-operations.generated.ts`;
      const typeName =
        words.map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join('') +
        'OperationTypes';
      if (!/^[A-Za-z]/.test(typeName)) {
        throw new Error(`Operation domain must start with a letter: ${name}`);
      }
      group = {
        name,
        fileName,
        typeName,
        operations: [],
      };
      if ([...groups.values()].some((existing) => existing.fileName === fileName)) {
        throw new Error(`Operation domains collide at ${fileName}`);
      }
      if ([...groups.values()].some((existing) => existing.typeName === typeName)) {
        throw new Error(`Operation domain types collide at ${typeName}`);
      }
      groups.set(name, group);
    }
    group.operations.push(operation);
  }
  return [...groups.values()].toSorted((left, right) => compareStrings(left.name, right.name));
}

export function operationDomainSource(
  domain: OperationDomain,
  aliases: ReadonlyMap<string, string>,
): string {
  const entries = domain.operations.map((operation) => operationToTypeEntry(operation, aliases));
  const body = entries.join('\n');
  const usedAliases = [...aliases.values()].filter((name) =>
    new RegExp(`\\b${name}\\b`).test(body),
  );
  const imports = usedAliases.length
    ? `import type { ${usedAliases.join(', ')} } from './shared-operation-types.generated.ts';`
    : '';
  return `${GENERATED_HEADER}\n${imports}\nexport type ${domain.typeName} = {\n${body}\n};\n`;
}

function operationToTypeEntry(
  operation: CatalogOperationSnapshot,
  aliases: ReadonlyMap<string, string>,
): string {
  const faults = operation.producibleFaults.length
    ? operation.producibleFaults.map((fault) => `'${fault}'`).join(' | ')
    : 'never';
  return `  '${operation.name}': {
    readonly input: ${renderRoot(schemaToNode(operation.inputSchema), aliases)};
    readonly output: ${renderRoot(schemaToNode(operation.outputSchema), aliases)};
    readonly faults: ${faults};
  };`;
}
